apiVersion: v1
kind: Secret
metadata:
  name: postgres-configuration
  namespace: awx
stringData:
  host: <external ip or url resolvable by the cluster>
  port: <external port, this usually defaults to 5432>
  database: <desired database name>
  username: <username to connect as>
  password: <password to connect with>
  sslmode: verify-full
  type: unmanaged
type: Opaque